### ISSUE TITLE
A Fase dois deve ser refatorada também

### ISSUE THREAD

**Issue by romulolink** [CaaporaGames/CaaporaOnline#2]

**Comment by mvteus** [comment]
As classes `Cobra.js`, `Cowboy.js`, `Cat.js` e `Caapora.js` estão acopladas ao `BasicGame.js`. Será necessário fazer essa desacoplagem primeiro para refatora-la.

**Comment by mvteus** [comment]
Exemplo da acoplagem na classe `Caapora.js`:

``` javascript
    // Inclui o Player do BasicGame como o Sprite
    this.basicGame.setPlayer(this.basicGame.add.isoSprite(x, y, 11, image, 0, this.basicGame.getIsoGroup()));
    // Pega a referencia do Player da Classe BasicGame
    player = this.basicGame.getPlayer();
```

**Comment by mvteus** [comment]
Uma idéia seria passar todos o atributos e métodos públicos para o arquivo `PhaserGame.js` para desacoplagem.

**Comment by romulolink** [comment]
Foi feita a desacoplagem na fase 1 e em seguida na fase 2
